services:

    desktop:
        container_name: desktop
        build:
            context: .
            args:
                - MESHCENTRAL_URL=$MESHCENTRAL_URL
        mem_limit: 2G
        environment:
            - AUTHORIZED_PUBLIC_KEYS=
            - MESHCENTRAL_DOMAIN=
            - MESHCENTRAL_GROUP_ID=
            - USER_PASSWORD=admin
        tmpfs:
            - /etc/X11/xorg.conf.d:size=16M
            - /tmp:exec
        volumes:
            - "./data-local:/media/user"
        ports:
            - "127.0.0.1:8022:22"
            - "127.0.0.1:8900:5900"
